</$objtype/mkfile
LIB=local.a$O
OFILES=pmac_done.$O pmac_file.$O pmac_init.$O pmac_memory.$O pmac_memory_multi.$O \
	pmac_ntz.$O pmac_process.$O pmac_shift_xor.$O pmac_test.$O 
HFILES=tomcrypt.h 

</sys/src/cmd/mklib

CC=pcc
LD=pcc
CFLAGS=-c -I. -I/sys/include/ape -I/386/include/ape -I../../../testprof/ -I../../headers/ \
	-D_POSIX_SOURCE -D_SUSV2_SOURCE -D_BSD_EXTENSION -D_RESEARCH_SOURCE -D_REENTRANT_SOURCE \
	-D_C99_SNPRINTF_EXTENSION -D_LIMITS_EXTENSION -D_REGEXP_EXTENSION -DLTC_SOURCE \
	-DLTC_NO_ASM -DLTC_NO_ROLC 

pmac_memory_multi.$O: /386/include/ape/stdarg.h 

nuke:V:
	mk clean
	rm -f $LIB
