<../mkconfig

DIRS=gen math plan9 posix stdio syscall

default:V:	all

install all:V:
	for(i in $DIRS $objtype)@{
		echo $i
		cd $i
		mk $MKFLAGS $target
	}
	cp /$objtype/lib/gnu/libap.a /$objtype/lib/gnu/libc.a

installall:V:
	for(objtype in $CPUS) mk $MKFLAGS install


clean nuke:V:
	for(i in $DIRS $CPUS)@{
		echo $i
		cd $i
		mk $MKFLAGS $target
	}
	rm -f /$objtype/lib/gnu/libc.a
