<../../mkconfig
LIB=/$objtype/lib/gnu/libap.a
OFILES=\
	cycles.$O\
	div.$O\
	getfcr.$O\
	lock.$O\
	main9.$O\
	main9p.$O\
	memmove.$O\
	memset.$O\
	notetramp.$O\
	setjmp.$O\
	strchr.$O\
	strcmp.$O\
	strcpy.$O\
	tas.$O\
	vlop.$O\
	vlrt.$O\

<../../mksyslib

CFLAGS=-c -D_POSIX_SOURCE -D_PLAN9_SOURCE

