</$objtype/mkfile
LIB=libsigsegv.a$O
OFILES=handler.$O stackvma.$O leave.$O dispatcher.$O version.$O handler-none.$O \
	stackvma-rofile.$O leave-nop.$O 

</sys/src/cmd/mklib

CC=pcc
LD=pcc
CFLAGS=-c -I. -I.. -B -D_POSIX_SOURCE -D_SUSV2_SOURCE -D_RESEARCH_SOURCE -D_REENTRANT_SOURCE \
	-D_BSD_EXTENSION -D_NET_EXTENSION -D_LIMITS_EXTENSION -D_C99_SNPRINTF_EXTENSION \
	-D_REGEXP_EXTENSION -DHAVE_SOCK_OPTS -DHAVE_CONFIG_H 

stackvma-rofile.$O: 
handler-none.$O: sigsegv.h 
version.$O: sigsegv.h 
dispatcher.$O: sigsegv.h 
leave.$O: leave-nop.c ../config.h 
stackvma.$O: stackvma-rofile.c ../config.h 
handler.$O: sigsegv.h handler-none.c ../config.h 

nuke:V:
	mk clean
	rm -f $LIB
