</$objtype/mkfile
LIB=libtilde.a$O
OFILES=tilde.$O shell.$O 
HFILES=../config.h 

</sys/src/cmd/mklib

CC=pcc
LD=pcc
CFLAGS=-c -I. -I.. -D_POSIX_SOURCE -D_SUSV2_SOURCE -D_RESEARCH_SOURCE -D_REENTRANT_SOURCE \
	-D_BSD_EXTENSION -D_NET_EXTENSION -D_LIMITS_EXTENSION -D_C99_SNPRINTF_EXTENSION \
	-D_REGEXP_EXTENSION -DHAVE_SOCK_OPTS -DHAVE_CONFIG_H 

shell.$O: 
tilde.$O: xmalloc.h tilde.h 

nuke:V:
	mk clean
	rm -f $LIB
