</$objtype/mkfile
LIB=libpoll.a$O
OFILES=poll.$O 
HFILES=poll.h 

</sys/src/cmd/mklib

CC=pcc
LD=pcc
CFLAGS=-c -B -I. -D_POSIX_SOURCE -D_SUSV2_SOURCE -D_BSD_EXTENSION 

poll.$O: 

install:V:
	mv libpoll.a$O /$objtype/lib/ape/libpoll.a
	cp poll.h.ape /sys/include/ape/poll.h

nuke:V:
	mk clean
	rm -f $LIB
