<../../config
LIB=/$objtype/lib/gnu/libap.a
OFILES=\
	cycles.$O\
	lock.$O\
	main9.$O\
	main9p.$O\
	memchr.$O\
	memcmp.$O\
	memcpy.$O\
	memmove.$O\
	memset.$O\
	notetramp.$O\
	setjmp.$O\
	strcat.$O\
	strchr.$O\
	strcmp.$O\
	strcpy.$O\
	strlen.$O\
	tas.$O\
	vlop.$O\
	vlrt.$O\

<../../mksyslib

CFLAGS=-c -D_POSIX_SOURCE -D_PLAN9_SOURCE

