<../mkconfig

LIB=/$objtype/lib/gnu/libv.a

OFILES=getpass.$O\
	tty.$O\
	rand.$O\
	nrand.$O\
	getfields.$O\
	min.$O\
	max.$O\
	error.$O\
	nap.$O

<../mksyslib

CFLAGS=-c

%.$O:	$FAMILY/%.c
	$CC $CFLAGS $prereq
