</$objtype/mkfile
TARG=agrep
OFILES=agrep.$O 
LIB=../lib/libtre.a 
BIN=/$objtype/bin
HFILES=../lib/regex.h ../lib/tre-config.h ../lib/tre.h ../config.h 

</sys/src/cmd/mkone

CC=pcc
LD=pcc
CFLAGS=-c -I. -I.. -I../lib -B -D_POSIX_SOURCE -D_SUSV2_SOURCE -D_RESEARCH_SOURCE \
	-D_PLAN9_SOURCE -D_REENTRANT_SOURCE -D_LIMITS_EXTENSION -D_NET_EXTENSION \
	-D_BSD_EXTENSION -D_C99_SNPRINTF_EXTENSION -D_REGEX_EXTENSION -DHAVE_CONFIG_H 

agrep.$O: 
