</$objtype/mkfile
LIB=libtre.a
OFILES=tre-match-backtrack.$O tre-parse.$O tre-stack.$O xmalloc.$O tre-match-approx.$O \
	regerror.$O tre-compile.$O regcomp.$O regexec.$O tre-ast.$O tre-mem.$O \
	tre-match-parallel.$O 
HFILES=xmalloc.h tre-internal.h ../config.h 

</sys/src/cmd/mklib

CC=pcc
LD=pcc
CFLAGS=-c -I. -I.. -B -D_POSIX_SOURCE -D_SUSV2_SOURCE -D_RESEARCH_SOURCE -D_PLAN9_SOURCE \
	-D_REENTRANT_SOURCE -D_LIMITS_EXTENSION -D_NET_EXTENSION -D_BSD_EXTENSION \
	-D_C99_SNPRINTF_EXTENSION -D_REGEX_EXTENSION -DHAVE_CONFIG_H -DHAVE_MBRTOWC \
	-DHAVE_ISBLANK 

tre-match-parallel.$O: tre.h tre-match-utils.h 
tre-mem.$O: tre-mem.h 
tre-ast.$O: tre-mem.h tre-ast.h 
regexec.$O: tre.h 
regcomp.$O: tre.h 
tre-compile.$O: tre.h tre-compile.h tre-parse.h tre-ast.h tre-stack.h tre-mem.h 
regerror.$O: tre.h 
tre-match-approx.$O: tre.h tre-match-utils.h 
xmalloc.$O: 
tre-stack.$O: tre-stack.h 
tre-parse.$O: tre-parse.h tre.h tre-stack.h tre-compile.h tre-mem.h tre-ast.h tre-mem.h 
tre-match-backtrack.$O: tre.h tre-match-utils.h tre-mem.h 

install:V:
	cp libtre.a /$objtype/lib/ape/

nuke:V:
	mk clean
	rm -f $LIB
